name: Backend Deploy

on:
  push:
    branches:
      - master
    paths:
      - "strapi_hcs/**"

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Strapi
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/project/strapi_hcs

            git pull origin master

            npm install

            npm run build

            pm2 restart strapi
