name: Deploy Fullstack (Strapi + Frontend)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            cd /var/www/project
            git pull

            # =====================
            # STRAPI
            # =====================
            cd strapi_hcs
            npm ci
            npm run build
            pm2 reload strapi

            # =====================
            # FRONTEND
            # =====================
            cd ../frontend
            npm ci
            npm run build

            rm -rf /var/www/frontend/*
            cp -r dist/* /var/www/frontend/ || cp -r build/* /var/www/frontend/
