name: Deploy Fullstack (Strapi + Frontend)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          timeout: 30m
          command_timeout: 30m
          script: |
            set -e

            echo "=== START ==="

            cd /var/www/project
            git pull

            echo "=== STRAPI INSTALL ==="
            cd strapi_hcs
            npm install

            echo "=== STRAPI BUILD ==="
            npm run build

            echo "=== RESTART STRAPI ==="
            pm2 reload strapi

            echo "=== FRONTEND INSTALL ==="
            cd ../frontend
            npm install

            echo "=== FRONTEND BUILD ==="
            npm run build

            echo "=== DONE ==="
